sudo: false
language: python
python:
- '3.6'
- '3.7'
install:
- pip install -r requirements.txt
script:
- pycodestyle csiroct_imbl_asci
- pytest --verbose --capture=no csiroct_imbl_asci
- pip install .
deploy:
  provider: pypi
  user: __token__
  password: pypi-AgEIcHlwaS5vcmcCJDcxNzc3YzU3LTUyNDgtNDU5Ni1hOWQyLTQ1ODU2NTc2YWM3ZQACJXsicGVybWlzc2lvbnMiOiAidXNlciIsICJ2ZXJzaW9uIjogMX0AAAYgvFyDbW4jZ9vK0IL-olBN9asp2vgpz9efkAIii9HUXUA
  on:
    tags: true
notifications:
  email: false
