sudo: false

language:
  - python

python:
  - 2.7
  - 3.6
  - 3.7

install:
  - pip install -r requirements.txt

script:
  - pycodestyle csiroct_imbl_asci
  - pytest --verbose --capture=no csiroct_imbl_asci
  - pip install .

notifications:
  email: false